name: Go AWS Workflow

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build
      run: go build
      
    - name: Run tests
      run: go test ./...
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: main
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: binary
        
    - name: Deploy to S3
      run: |
        aws s3 mb s3://account-1bucket1 --region us-east-1
        aws s3api put-public-access-block --bucket account-1bucket1 --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
        aws s3 mb s3://account2bucket1 --region us-east-1  
        aws s3api put-public-access-block --bucket account2bucket1 --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
        aws s3 mb s3://account2bucket2 --region us-east-1
        aws s3api put-public-access-block --bucket account2bucket2 --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
        aws s3 mb s3://testbucket --region us-east-1
        aws s3api put-public-access-block --bucket testbucket --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"