name: AWS Go S3 Buckets CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:

  build:
    name: Build Go Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
        
    - name: Build
      run: go build ./...
      
    - name: Run Tests
      run: go test ./...
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: go-app
        path: |
          *.go
          go.mod
          go.sum
        
  deploy:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: go-app
        
    - name: Deploy S3 Buckets
      run: |
        aws s3 mb s3://account-1bucket1 --region ${{ env.AWS_REGION }} --bucket-public-access-block="PublicAccessBlockConfiguration={BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true}"
        aws s3 mb s3://account2bucket1 --region ${{ env.AWS_REGION }} --bucket-public-access-block="PublicAccessBlockConfiguration={BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true}"
        aws s3 mb s3://account2bucket2 --region ${{ env.AWS_REGION }} --bucket-public-access-block="PublicAccessBlockConfiguration={BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true}"
        aws s3 mb s3://Test-Bucket --region ${{ env.AWS_REGION }} --bucket-public-access-block="PublicAccessBlockConfiguration={BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true}"